# -*- coding: utf-8 -*-
"""ncdcNews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5OIX9zv9q4jwacXTQgB-R9v8rqW-T8-
"""

import urllib.request
from bs4 import BeautifulSoup
import requests
def ncdcNews():

  url = "http://ncdc.gov.ng/news/press"

  # Open the URL as Browser, not as python urllib
  page=urllib.request.Request(url,headers={'User-Agent': 'Mozilla/5.0'}) 
  infile=urllib.request.urlopen(page).read()
  # Read the content as string decoded with ISO-8859-1
  data = infile.decode('ISO-8859-1')
  soup = BeautifulSoup(data, 'html.parser')
  #get the news title, link and news details
  Links= soup.findAll('a', {'class': 'white-text'})
  Links=[i.get('href') for i in Links]
  Titles=soup.select("article h3")
  Titles=[i.get_text() for i in Titles]
  NewsDetail=soup.find_all('article')
  NewsDetail=[i.get_text() for i in NewsDetail]
  
  NewsData = []
  for i in range(0,len(Links)):
    NewsDictinary = {}
    NewsDictinary['Title'] = Titles[i]
    NewsDictinary['NewsDetail'] = NewsDetail[i]
    NewsDictinary['Link']= Links[i]
    NewsData.append(NewsDictinary)
  # convert list to json
  import json
  data_json = json.dumps(NewsData)
  return(data_json)

